Repository welpo/tabi, pull requests merged in 2023-09, with the labels that each got.

#128 ✨ feat(settings): add hierarchy-based setting overrides
  config.toml
  content/blog/javascript.ca.md
  content/blog/javascript.es.md
  content/blog/javascript.md
  content/blog/markdown.ca.md
  content/blog/markdown.es.md
  content/blog/markdown.md
  templates/base.html
  templates/macros/content.html
  templates/macros/settings.html
  templates/partials/footer.html
  theme.toml
Labels: enhancement

#129 ♻️ refactor(translation): streamline translation logic with macro
  static/feed_style.xsl
  templates/404.html
  templates/archive.html
  templates/atom.xml
  templates/base.html
  templates/macros/add_comments.html
  templates/macros/content.html
  templates/macros/format_date.html
  templates/macros/list_posts.html
  templates/macros/paginate.html
  templates/macros/set_title.html
  templates/macros/table_of_contents.html
  templates/macros/translate.html
  templates/partials/footer.html
  templates/partials/nav.html
  templates/shortcodes/multilingual_quote.html
  templates/tags/list.html
  templates/tags/single.html
Labels: enhancement

#131 💄 style(code blocks): change syntax highlighting theme & text size
  content/blog/comments.ca.md
  content/blog/comments.es.md
  content/blog/comments.md
  content/blog/markdown.ca.md
  content/blog/markdown.es.md
  content/blog/markdown.md
  content/blog/toc.ca.md
  content/blog/toc.es.md
  content/blog/toc.md
  sass/main.scss
  sass/parts/_code.scss
  sass/parts/_syntax_theme.scss
  sass/syntax/syntax-ayu-dark.scss
Labels: enhancement

#140 ♿️ feat(a11y): update heading tags
  sass/main.scss
  sass/parts/_home-banner.scss
  sass/parts/_misc.scss
  sass/parts/_posts_list.scss
  templates/macros/cards_pages.html
  templates/macros/content.html
  templates/macros/list_posts.html
  templates/macros/page_desc.html
  templates/macros/page_header.html
Labels: bug

#142 ✨ feat(title): add `invert_title_order` config option
  config.toml
  templates/macros/set_title.html
  theme.toml
Labels: enhancement

#143 ✨ feat: add `browser_theme_color` config option
  config.toml
  templates/partials/header.html
  theme.toml
Labels: enhancement

#144 🐛 fix: allow live reload when zola is in `serve` mode
  templates/partials/header.html
Labels: bug

#145 🌐 feat(i18n): overhaul translation system & add languages
  .githooks/pre-commit
  CONTRIBUTING.md
  README.md
  config.toml
  content/blog/faq-languages.ca.md
  content/blog/faq-languages.es.md
  content/blog/faq-languages.md
  i18n/ca.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/it.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/pt.toml
  i18n/ru.toml
  i18n/uk.toml
  i18n/zh.toml
  sass/parts/_header.scss
  static/custom_subset.css
  static/feed_style.xsl
  templates/404.html
  templates/archive.html
  templates/atom.xml
  templates/base.html
  templates/cards.html
  templates/macros/add_comments.html
  templates/macros/content.html
  templates/macros/format_date.html
  templates/macros/list_posts.html
  templates/macros/paginate.html
  templates/macros/set_title.html
  templates/macros/table_of_contents.html
  templates/macros/translate.html
  templates/page.html
  templates/partials/footer.html
  templates/partials/header.html
  templates/partials/language_switcher.html
  templates/partials/nav.html
  templates/section.html
  templates/shortcodes/multilingual_quote.html
  templates/tags/list.html
  templates/tags/single.html
  theme.toml
Labels: bug, documentation, enhancement

#147 ✨ feat(templates): introduce info-page template
  config.toml
  content/pages/_index.ca.md
  content/pages/_index.es.md
  content/pages/_index.md
  content/pages/about.ca.md
  content/pages/about.es.md
  content/pages/about.md
  i18n/ca.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/it.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/pt.toml
  i18n/ru.toml
  i18n/uk.toml
  i18n/zh.toml
  sass/parts/_misc.scss
  static/custom_subset.css
  static/img/social_cards/about.ca.jpg
  static/img/social_cards/about.es.jpg
  static/img/social_cards/about.jpg
  templates/info-page.html
  templates/page.html
  templates/partials/extra_features.html
  theme.toml
Labels: enhancement

#153 ✨ feat(header): add img_alt attribute for customisable alt text
  README.md
  content/_index.ca.md
  content/_index.es.md
  content/_index.md
  static/img/social_cards/es.jpg
  templates/partials/home_banner.html
Labels: enhancement

#154 🔍️ feat: enhance SEO and accessibility with meta tags
  templates/partials/header.html
  templates/partials/multilingual_tags.html
Labels: enhancement

#156 ✨ feat(alias): style redirect page
  sass/main.scss
  templates/internal/alias.html
Labels: enhancement

#157 ✨ feat: allow internal project links
  content/projects/_index.ca.md
  content/projects/_index.es.md
  content/projects/_index.md
  content/projects/chu.ca.md
  content/projects/chu.es.md
  content/projects/chu.md
  content/projects/nani.ca.md
  content/projects/nani.es.md
  content/projects/nani.md
  content/projects/spectro.ca.md
  content/projects/spectro.es.md
  content/projects/spectro.md
  content/projects/tabi.ca.md
  content/projects/tabi.es.md
  content/projects/tabi.md
  static/img/ca_projects.jpg
  static/img/ca_projects_nani.jpg
  static/img/ca_projects_spectro.jpg
  static/img/ca_projects_tabi.jpg
  static/img/es_projects_chu.jpg
  static/img/es_projects_nani.jpg
  static/img/es_projects_spectro.jpg
  static/img/es_projects_tabi.jpg
  static/img/light_dark_tabi.webp
  static/img/projects_chu.jpg
  static/img/projects_nani.jpg
  static/img/projects_tabi.jpg
  static/img/social_cards/ca_projects.jpg
  static/img/social_cards/ca_projects_chu.jpg
  static/img/social_cards/ca_projects_nani.jpg
  static/img/social_cards/ca_projects_spectro.jpg
  static/img/social_cards/es_projects.jpg
  static/img/social_cards/es_projects_chu.jpg
  static/img/social_cards/es_projects_nani.jpg
  static/img/social_cards/es_projects_spectro.jpg
  static/img/social_cards/es_projects_tabi.jpg
  static/img/social_cards/projects.jpg
  static/img/social_cards/projects_chu.jpg
  static/img/social_cards/projects_nani.jpg
  static/img/social_cards/projects_tabi.jpg
  static/img/spectrogram.webp
  templates/partials/cards_pages.html
Labels: documentation, enhancement

#159 🐛 fix(header): check if translations exist while building tags
  templates/partials/multilingual_tags.html
Labels: bug

#163 ✨ feat(social-media-cards): allow colocated paths
  templates/partials/header.html
Labels: enhancement

#164 ✨ feat(atom): add `full_content_in_feed` option
  config.toml
  templates/atom.xml
  theme.toml
Labels: enhancement

#169 📝 docs: add guide to all of tabi's features
  README.md
  config.toml
  content/blog/mastering-tabi-settings.ca.md
  content/blog/mastering-tabi-settings.es.md
  content/blog/mastering-tabi-settings.md
  content/projects/tabi.ca.md
  content/projects/tabi.es.md
  content/projects/tabi.md
  static/img/browser_theme_colour_dark.webp
  static/img/browser_theme_colour_light.webp
  static/img/commit_history_dark.webp
  static/img/commit_history_light.webp
  static/img/copy_button_on_code_blocks_dark.webp
  static/img/copy_button_on_code_blocks_light.webp
  static/img/copyright_dark.webp
  static/img/copyright_light.webp
  static/img/footnote_backlinks_dark.webp
  static/img/footnote_backlinks_light.webp
  static/img/header_dark.webp
  static/img/header_light.webp
  static/img/quick_navigation_buttons_dark.webp
  static/img/quick_navigation_buttons_light.webp
  static/img/see_changes_dark.webp
  static/img/see_changes_light.webp
  static/img/site_source_dark.webp
  static/img/site_source_light.webp
  static/img/with_social_media_card.webp
  theme.toml
Labels: documentation, enhancement

#166 Chinese translations
  i18n/zh-Hans.toml
  i18n/zh-Hant.toml
Labels: enhancement, i18n

#173 Update Globe icon with lighter version
  sass/parts/_header.scss
Labels: enhancement

#179 ✨ feat(SEO): Add description support for sections
  templates/partials/header.html
Labels: enhancement
