Repository welpo/tabi, pull requests merged in 2023-10, with the labels that each got.

#183 ♿️ fix: improve accessibility and i18n
  i18n/ca.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/it.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/pt-PT.toml
  i18n/ru.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  i18n/zh-Hant.toml
  sass/parts/_header.scss
  sass/parts/_misc.scss
  sass/parts/_theme-switch.scss
  static/js/copyCodeToClipboard.js
  static/js/copyCodeToClipboard.min.js
  static/js/themeSwitcher.js
  static/js/themeSwitcher.min.js
  templates/partials/extra_features.html
  templates/partials/language_switcher.html
  templates/partials/nav.html
  templates/partials/theme_switcher.html
Labels: bug, enhancement, i18n

#186 ⚡️ feat(fonts): optimise font size
  sass/main.scss
  static/fonts/CascadiaCode-SemiLight.woff2
  static/fonts/Inter4.woff2
  static/fonts/SourceSerif4Variable-Roman.otf.woff2
  static/fonts/SourceSerif4Variable-Roman.ttf.woff2
Labels: enhancement

#193 ✨feat: support privacy-respecting analytics
  config.toml
  content/blog/mastering-tabi-settings.ca.md
  content/blog/mastering-tabi-settings.es.md
  content/blog/mastering-tabi-settings.md
  content/blog/security.ca.md
  content/blog/security.es.md
  content/blog/security.md
  templates/partials/analytics.html
  templates/partials/content_security_policy.html
  templates/partials/header.html
  theme.toml
Labels: enhancement

#196 🐛 fix(hyvor-talk): switch from ID to class selector for initialisation
  static/js/hyvortalk.js
  static/js/hyvortalk.min.js
Labels: bug

#197 ✨ feat(footer): add configurable footer menu
  config.toml
  content/blog/mastering-tabi-settings.ca.md
  content/blog/mastering-tabi-settings.es.md
  content/blog/mastering-tabi-settings.md
  i18n/ca.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/it.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/pt-PT.toml
  i18n/ru.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  i18n/zh-Hant.toml
  sass/parts/_footer.scss
  static/custom_subset.css
  templates/partials/footer.html
  theme.toml
Labels: enhancement

#198 ✨ feat(theme-switcher): add theme reset button
  content/blog/javascript.ca.md
  content/blog/javascript.es.md
  content/blog/javascript.md
  i18n/ca.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/it.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/pt-PT.toml
  i18n/ru.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  i18n/zh-Hant.toml
  sass/parts/_theme-switch.scss
  static/js/themeSwitcher.js
  static/js/themeSwitcher.min.js
  templates/partials/theme_switcher.html
Labels: enhancement

#203 ✨ feat(list_posts.html): display draft status in post list
  sass/parts/_posts_list.scss
  templates/macros/list_posts.html
Labels: enhancement

#207 🐛 fix(stylised-feed): set proper date class
  static/feed_style.xsl
Labels: bug

#211 🐛 fix(comments): fix malformed URLs in Isso mails
  config.toml
  templates/partials/comments.html
  theme.toml
Labels: bug

#216 ✨ feat(comments): allow page override of global system
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  templates/page.html
Labels: enhancement

#218 💄 fix(style): proper nested lists spacing
  sass/main.scss
Labels: bug

#219 🐛 fix(footer): fix external link redirection in footer
  config.toml
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  templates/partials/footer.html
  theme.toml
Labels: bug
