Repository welpo/tabi, pull requests merged in 2024-11, with the labels that each got.

#423 ✨ feat(shortcodes): support body admonitions
  content/blog/shortcodes/index.ca.md
  content/blog/shortcodes/index.es.md
  content/blog/shortcodes/index.md
  templates/shortcodes/admonition.html
Labels: enhancement

#406 ✨ feat: introduce a 'series of post' feature
  README.md
  config.toml
  content/blog/mastering-tabi-settings/img/jump_to_series_posts_dark.webp
  content/blog/mastering-tabi-settings/img/jump_to_series_posts_light.webp
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  content/blog/series/img/jump_to_series_posts_dark.webp
  content/blog/series/img/jump_to_series_posts_light.webp
  content/blog/series/img/series_dark.webp
  content/blog/series/img/series_light.webp
  content/blog/series/img/series_reversed_dark.webp
  content/blog/series/img/series_reversed_light.webp
  content/blog/series/index.ca.md
  content/blog/series/index.es.md
  content/blog/series/index.md
  content/blog/series/social_cards/blog_series.jpg
  content/blog/series/social_cards/ca_blog_series.jpg
  content/blog/series/social_cards/es_blog_series.jpg
  content/projects/tabi/index.ca.md
  content/projects/tabi/index.es.md
  content/projects/tabi/index.md
  i18n/ar.toml
  i18n/ca.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/et.toml
  i18n/fa.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/it.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/nl.toml
  i18n/or.toml
  i18n/pt-PT.toml
  i18n/ru.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  i18n/zh-Hant.toml
  sass/parts/_misc.scss
  sass/parts/_posts_list.scss
  static/feed_style.xsl
  templates/base.html
  templates/macros/list_posts.html
  templates/macros/series_page.html
  templates/page.html
  templates/partials/extra_features.html
  templates/partials/paginate.html
  templates/series.html
  theme.toml
Labels: enhancement

#425 💄 style: improve navigation bar & metadata wrapping
  sass/parts/_header.scss
  templates/page.html
  templates/partials/nav.html
Labels: enhancement

#424 ✨ feat: add pinned posts functionality
  README.md
  content/_index.ca.md
  content/_index.es.md
  content/_index.md
  content/blog/_index.ca.md
  content/blog/_index.es.md
  content/blog/_index.md
  content/blog/mastering-tabi-settings/img/pinned_post_dark.webp
  content/blog/mastering-tabi-settings/img/pinned_post_light.webp
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  i18n/ar.toml
  i18n/ca.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/et.toml
  i18n/fa.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/it.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/nl.toml
  i18n/or.toml
  i18n/pt-PT.toml
  i18n/ru.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  i18n/zh-Hant.toml
  sass/parts/_posts_list.scss
  templates/macros/list_posts.html
  templates/partials/main_page_posts_list.html
Labels: enhancement

#427 🐛 fix: Isso comments in multilingual setups
  templates/page.html
Labels: bug

#428 ✨ feat: allow pinned post with pagination
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  templates/macros/list_posts.html
  templates/partials/main_page_posts_list.html
  templates/section.html
Labels: enhancement

#429 💄 style: set accent color to match theme
  sass/main.scss
Labels: enhancement

#430 💄 style: colour scrollbar to match primary colour
  sass/main.scss
Labels: enhancement

#432 🐛 fix: support relative paths in inherited social media card
  config.toml
  content/_index.ca.md
  content/_index.es.md
  content/_index.md
  content/archive/_index.ca.md
  content/archive/_index.es.md
  content/archive/_index.md
  content/archive/archive.jpg
  content/archive/ca_archive.jpg
  content/archive/es_archive.jpg
  content/blog/_index.ca.md
  content/blog/_index.es.md
  content/blog/_index.md
  content/blog/blog.jpg
  content/blog/ca_blog.jpg
  content/blog/es_blog.jpg
  content/ca.jpg
  content/es.jpg
  content/index.jpg
  content/pages/about/index.ca.md
  content/pages/about/index.es.md
  content/pages/about/index.md
  content/pages/about/social_cards/about.ca.jpg
  content/pages/about/social_cards/about.es.jpg
  content/pages/about/social_cards/about.jpg
  content/projects/_index.ca.md
  content/projects/_index.es.md
  content/projects/_index.md
  content/projects/ca_projects.jpg
  content/projects/es_projects.jpg
  content/projects/projects.jpg
  templates/partials/header.html
  templates/partials/social_media_images.html
Labels: bug

#438 💄 style: fix home banner layout for short intro
  sass/parts/_home-banner.scss
Labels: bug

#441 📝 docs: add tabi-start integration
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  config.toml
  content/_index.ca.md
  content/_index.es.md
  content/_index.md
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  theme.toml
Labels: documentation
