Repository welpo/tabi, pull requests merged in 2024-10, with the labels that each got.

#413 🐛 fix: update CSP for GoatCounter
  templates/partials/content_security_policy.html
Labels: bug

#412 💥 feat: force LTR rendering for code blocks
  config.toml
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  sass/parts/_code.scss
  templates/base.html
  templates/page.html
  theme.toml
Labels: i18n

#421 Fix typo in README.md
  README.md
Labels: documentation
