Repository welpo/tabi, pull requests merged in 2024-07, with the labels that each got.

#350 🐛 fix(search): close modal when clicking current page result
  static/js/searchElasticlunr.js
  static/js/searchElasticlunr.min.js
Labels: bug

#354 ⬆️ chore(deps): update KaTeX to v0.16.11
  static/js/katex.min.js
  static/katex.min.css
Labels: dependencies

#330 ✨ feat: add date visibility options to post list
  config.toml
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  sass/main.scss
  sass/parts/_posts_list.scss
  static/feed_style.xsl
  templates/atom.xml
  templates/macros/list_posts.html
  theme.toml
Labels: enhancement

#357 ✨ feat: follow user OS theme with JS disabled
  config.toml
  content/blog/customise-tabi/index.ca.md
  content/blog/customise-tabi/index.es.md
  content/blog/customise-tabi/index.md
  sass/main.scss
  static/feed_style.xsl
  templates/atom.xml
  theme.toml
Labels: enhancement

#358 🐛 fix(header): render feed links based on config
  templates/partials/header.html
Labels: bug

#359 💄 style(error): enhance visibility of Zola errors
  sass/main.scss
  sass/parts/_zola-error.scss
Labels: enhancement
