Repository welpo/tabi, pull requests merged in 2024-02, with the labels that each got.

#265 🌐 feat(i18n): add Arabic language
  i18n/ar.toml
Labels: help wanted, i18n

#272 🐛 fix(i18n): fix arrows in RTL languages
  sass/parts/_misc.scss
  static/feed_style.xsl
  templates/macros/list_posts.html
  templates/page.html
  templates/partials/paginate.html
  templates/tags/single.html
  templates/taxonomy_single.html
Labels: bug

#280 ✨ feat(shortcodes): support URLs for image source
  content/blog/shortcodes/index.ca.md
  content/blog/shortcodes/index.es.md
  content/blog/shortcodes/index.md
  templates/shortcodes/dimmable_image.html
  templates/shortcodes/dual_theme_image.html
  templates/shortcodes/full_width_image.html
  templates/shortcodes/image_hover.html
  templates/shortcodes/image_toggler.html
  templates/shortcodes/invertible_image.html
Labels: enhancement
