Repository welpo/tabi, pull requests merged in 2025-01, with the labels that each got.

#458 ✨ feat: support disabling of the font-subset in header
  config.toml
  content/blog/custom-font-subset/index.ca.md
  content/blog/custom-font-subset/index.es.md
  content/blog/custom-font-subset/index.md
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  templates/partials/header.html
  theme.toml
Labels: enhancement

#465 🐛 fix: remove `nofollow` robots meta tag
  templates/partials/header.html
Labels: bug

#467 🐛 fix(feed): load CSS in subfolder setups
  static/feed_style.xsl
Labels: bug

#471 🔒️ fix(header): reposition include of CSP partial
  templates/partials/header.html
Labels: bug, enhancement
