Repository welpo/tabi, pull requests merged in 2025-02, with the labels that each got.

#481 🐛 fix: support external URLs in menu
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  templates/partials/nav.html
Labels: bug

#482 ♿️ fix: improve menu accessibility
  sass/parts/_header.scss
  templates/partials/nav.html
Labels: bug

#483 💥 feat(archive)!: enforce chronological sorting
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  templates/archive.html
Labels: enhancement, 💥 breaking change

#484 ✨ feat: render section content
  templates/section.html
Labels: enhancement

#443 ✨ feat: add indicator to external links
  config.toml
  content/blog/mastering-tabi-settings/img/external_link_dark.webp
  content/blog/mastering-tabi-settings/img/external_link_light.webp
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  sass/parts/_misc.scss
  templates/page.html
Labels: enhancement

#486 ✨ feat: render markdown in page titles & descriptions
  templates/archive.html
  templates/page.html
  templates/partials/cards_pages.html
Labels: enhancement

#489 ✨ feat: support Zola's native code block names
  config.toml
  content/blog/javascript/index.ca.md
  content/blog/javascript/index.es.md
  content/blog/javascript/index.md
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  content/blog/series/index.ca.md
  content/blog/series/index.es.md
  content/blog/series/index.md
  content/blog/shortcodes/index.ca.md
  content/blog/shortcodes/index.es.md
  content/blog/shortcodes/index.md
  content/projects/doteki/index.ca.md
  content/projects/doteki/index.es.md
  content/projects/doteki/index.md
  sass/parts/_code.scss
  static/js/addSrcToCodeBlock.js
  static/js/addSrcToCodeBlock.min.js
  static/js/codeBlockNameLinks.js
  static/js/codeBlockNameLinks.min.js
  templates/partials/extra_features.html
  theme.toml
Labels: enhancement

#490 ✨ feat: add `hide_from_main_feed` support
  content/blog/mastering-tabi-settings/index.ca.md
  content/blog/mastering-tabi-settings/index.es.md
  content/blog/mastering-tabi-settings/index.md
  templates/atom.xml
Labels: enhancement

#390 🌐 docs(demo): basic arabic translation
  config.toml
  content/_index.ar.md
  content/ar.jpg
  content/archive/_index.ar.md
  content/blog/_index.ar.md
  content/blog/markdown/index.ar.md
  content/pages/_index.ar.md
  content/pages/about/index.ar.md
  content/pages/about/social_cards/about.ar.jpg
  content/pages/privacy/index.ar.md
  content/projects/_index.ar.md
  content/projects/tabi/index.ar.md
Labels: documentation, enhancement, i18n
